I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/rpy/script.rpy", line 7, in script call
    call Chapter11
  File "game/rpy/chapter/Chapter11.rpy", line 82, in script
    mir_amazing  "...?"
Exception: Sayer 'mir_amazing' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/rpy/script.rpy", line 7, in script call
    call Chapter11
  File "game/rpy/chapter/Chapter11.rpy", line 82, in script
    mir_amazing  "...?"
  File "E:\p\renpy\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "E:\p\renpy\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "E:\p\renpy\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'mir_amazing' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.4.24120703
DeathDetached 1.0
Fri Jan  3 16:34:37 2025
